project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    grid:
      sidebar-width: 300px
      body-width: 1300px
      margin-width: 300px
      gutter-width: 1.5rem



